# Site settings
title: Voxelgon
email: VoxelgonGame@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Voxelgon is a DF-Like space game, featuring dual modes between flying your ship and managing its crew.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://voxelgon.github.io" # the base hostname & protocol for your site
twitter_username: cineboxandrew
github_username:  cineboxandrew

# Build settings
markdown: kramdown
